// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCkaaDfDEShIhj5efBUqc_JD5T4CgNvtkY',
    appId: '1:776481681864:web:13ae1ed050e9a9fc3010fd',
    messagingSenderId: '776481681864',
    projectId: 'todoku-c9d2f',
    authDomain: 'todoku-c9d2f.firebaseapp.com',
    storageBucket: 'todoku-c9d2f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD9myFh0g4oWgjnJ9C-cY_lzExv2vMYW5g',
    appId: '1:776481681864:android:245875ac7f15b5923010fd',
    messagingSenderId: '776481681864',
    projectId: 'todoku-c9d2f',
    storageBucket: 'todoku-c9d2f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBgqJOxXY1Ss5nPwFUdiJvhSyeb3zq09m0',
    appId: '1:776481681864:ios:bc013a7f9bdeef5b3010fd',
    messagingSenderId: '776481681864',
    projectId: 'todoku-c9d2f',
    storageBucket: 'todoku-c9d2f.appspot.com',
    iosBundleId: 'com.example.todokuApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBgqJOxXY1Ss5nPwFUdiJvhSyeb3zq09m0',
    appId: '1:776481681864:ios:bc013a7f9bdeef5b3010fd',
    messagingSenderId: '776481681864',
    projectId: 'todoku-c9d2f',
    storageBucket: 'todoku-c9d2f.appspot.com',
    iosBundleId: 'com.example.todokuApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCkaaDfDEShIhj5efBUqc_JD5T4CgNvtkY',
    appId: '1:776481681864:web:b40a8034172f56973010fd',
    messagingSenderId: '776481681864',
    projectId: 'todoku-c9d2f',
    authDomain: 'todoku-c9d2f.firebaseapp.com',
    storageBucket: 'todoku-c9d2f.appspot.com',
  );
}
